dist: trusty
sudo: required
addons:
  chrome: stable
language: node_js
node_js:
  - "lts/carbon"

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

script:
  - npm run lint
  - npm run build
  - npm test
